NDEBUG=0
STATIC=1
SHARED=0
LCOV=0

TARGETDIR=../lib
NAME=libstatic.a

SRC+=$(shell find ./ -name "*.cpp")

#INC=-I./

#LIB_DIR+=./

CXXFLAGS+=-Wall -Wno-deprecated -Wno-unused-function

include ../makefile.pub

